### PR TITLE
Update to latest rancher + changes needed for v2

### PR DESCRIPTION
**Pull request by alena1108**
Schema to the latest rancher
Also changed schema builder to put the concrete type instead of interface{} for non-reference array elements. 

Example:

```
PublicEndpoints []interface{} `json:"publicEndpoints,omitempty" yaml:"public_endpoints,omitempty"`
```

will be 

```
PublicEndpoints []PublicEndpoint `json:"publicEndpoints,omitempty" yaml:"public_endpoints,omitempty"`
```

### CODE REVIEW

**Comment by alena1108** [comment]
@ibuildthecloud wonder if it should be []*Resource instead of []Resource, what do you think?

**Comment by cloudnautique** [comment]
The collections Data should be []*Resource as well?

**Comment by alena1108** [comment]
@cloudnautique that I don't know. I've only modified resource definitions for fields having type=concreteType defined in v1 schema.

**Comment by cloudnautique** [comment]
I'm using your version of the client against V1, and I like the []*Resource idea, but when I got the collection, I had to do this: https://github.com/cloudnautique/rbs-sandbox/blob/master/main.go#L170
So I could append to Data and send it back. Keep in mind my solution might be terrible and non-idomatic :)

**Comment by alena1108** [comment]
@cloudnautique ic the problem. I will keep it as a []Resource for now then.

**Pull request closed without merging**
