### PR TITLE
upgrade to the latest cattle

### PR DESCRIPTION
**Pull request by wlan0**
@cjellick @ibuildthecloud 

I'm testing this change with my local gms to make sure everything works all right. Please don't merge yet.

### CODE REVIEW

**Comment by wlan0** [comment]
gms works well with these changes.

**Comment by wlan0** [comment]
The docker daemon is not running. 

The command  `docker version` returns a non-zero exit status if the docker client cannot reach the docker daemon.

That is stopping the entire ci process.

**Comment by cjellick** [comment]
Shoot. Its because the build didnt have privileged turned on

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
