### PR TITLE
Support creation of vmware hosts

### PR DESCRIPTION
**Pull request by bestrand**
Added config for creating vmware hosts through either v1 machine or v2 host. 

Not done many PR's so let me know if anything has to be changed.

### CODE REVIEW

**Comment by cjellick** [comment]
@golvteppe What is the intent of this PR? Meaning, where do you intend to use the generated structs? They are not directly needed by any existing Rancher code. VMWare hosts can be added as long as there is a valid docker machine driver configured in Rancher

**Comment by cjellick** [comment]
To explain why I ask: we auto-generate all the code in this repo based off the the schemas present in the API when rancher/server is started. Since vmware is not enabled by default, this would just get deleted the next time we generate the code

**Comment by golvteppe** [comment]
@cjellick Ah, I have misunderstood where the code is coming from then :) I use the struct (just v2 version now / in host struct) in Terraform code and we create VMware hosts through Terraform. We are only using VMware as machine driver at the moment through Terraform, so kind of dependent on this struct in go-rancher. Would it be possible to activate this and add it? I think it is added in the rancher/go-rancher v2 branch already, but then again that seems outdated.

If there are other ways to trigger creation of VMware hosts through go, I can use them instead.

**Comment by vincent99** [comment]
If there isn't already there really needs to be a generic way to use drivers without involving generating every possible driver you might want to use, because users can upload their own arbitrary drivers.

HostTemplates in 2.0 might mostly solve this already since the `publicValues` and `secretValues` are arbitrary JSON fields.

**Comment by golvteppe** [comment]
So if I understand correctly go-rancher will not be supporting creation of VMware hosts? Since the rancher provider in terraform soon will use "github.com/rancher/go-rancher/v2" as client, I am kinda stuck with that option if I want to use the offical release (I assume). I can try removing the struct and see what happens when the data is passed on to go-rancher from terraform. 

It is also possible to create VMware hosts through the rancher cli (atleast v0.5.1), so I just assumed that VMware would be something that would be included in go-rancher aswell.

**Comment by cjellick** [comment]
@vincent99 A generic way to use drivers *in this specific go-rancher repo*, or just with the API in general?

Because this repo isnt really intended to support that at this point. I'm not sure if this has an impact on how rancher-compose adds hosts, but I imagine it might.

**Comment by cjellick** [comment]
Very stale. Closing. Thanks! Please open a new PR if there is still a relevant change.

**Pull request closed without merging**
